apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: root
    namespace: argo-cd
spec:
    destination:
        namespace: argo-cd
        server: 'https://kubernetes.default.svc'
    source:
        path: apps/
        repoURL: 'https://github.com/keskad/test-argo-tekton'
        targetRevision: HEAD
    project: default
    syncPolicy:
        automated:
            prune: false
            selfHeal: false
        syncOptions:
            - ApplyOutOfSyncOnly=true
