---
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
    name: example-go-1
    namespace: go-cicd
spec:
    url: "https://github.com/keskad/pipelines-as-code-test-example-go-1"
    git_provider:
        user: keskad
        secret:
            name: pac-git-basic-auth-root-example-go-1
            key: token
