---
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
    name: example-go-1
    namespace: go-cicd
spec:
    url: "https://github.com/keskad/pipelines-as-code-test-example-go-1"
    git_provider:
        user: keskad
        secret:
            name: pac-git-basic-auth-root-example-go-1
            key: token

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    finalizers:
        - kubernetes.io/pvc-protection
    name: maven-cache
    namespace: go-cicd
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: local-path
