---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: test-pipeline
    namespace: argo-cd
spec:
    destination:
        namespace: 'damiank-tekton-cicd'
        server: 'https://kubernetes.default.svc'
    source:
        path: src/test-pipeline
        repoURL: 'https://github.com/keskad/test-argo-tekton'
        targetRevision: HEAD
    project: default
    syncPolicy:
        automated:
            prune: false
            selfHeal: false
        syncOptions:
            - CreateNamespace=true
            - ApplyOutOfSyncOnly=true
