---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pipeline-spawner-sa
rules:
    # Permissions for every EventListener deployment to function
    - apiGroups: ["triggers.tekton.dev"]
      resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
      verbs: ["get"]
    - apiGroups: [""]
        # secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
      resources: ["configmaps", "secrets", "serviceaccounts"]
      verbs: ["get", "list", "watch"]
    # Permissions to create resources in associated TriggerTemplates
    - apiGroups: ["tekton.dev"]
      resources: ["pipelineruns", "pipelineresources", "taskruns"]
      verbs: ["create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pipeline-spawner-sa
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pipeline-spawner-sa
subjects:
    - kind: ServiceAccount
      name: pipeline-spawner-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pipeline-spawner-read-only-global-resources
rules:
    - apiGroups: ["triggers.tekton.dev"]
      resources: ["clusterinterceptors"]
      verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: tekton-crb-ro-damiank-tekton-cicd
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pipeline-spawner-read-only-global-resources
subjects:
    - kind: ServiceAccount
      name: pipeline-spawner-sa
      namespace: damiank-tekton-cicd
